### ISSUE TITLE
Allow the user to choose the validation level

### ISSUE THREAD

**Issue by Klortho** [JATS4R/jats4r.github.io#11]
<a href="https://github.com/hubgit"><img src="https://avatars.githubusercontent.com/u/14294?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [hubgit](https://github.com/hubgit)**
_Friday Jan 23, 2015 at 15:54 GMT_
_Originally opened as https://github.com/JATS4R/validation/issues/8_

---

May involve using a particular stylesheet or passing particular variables into the transformation.

**Comment by Klortho** [comment]
<a href="https://github.com/hubgit"><img src="https://avatars.githubusercontent.com/u/14294?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hubgit](https://github.com/hubgit)**
_Thursday Apr 02, 2015 at 14:36 GMT_

---

Offer choice of:
- [ ] errors
- [ ] warnings
- [ ] tagging information

and use the appropriate XSL accordingly.

**Comment by Klortho** [comment]
This is done:  http://jats4r.github.io/validate/
I also added a "revalidate" button, so that you can re-validate the same file, at a different level, without having to re-select it with the file-select box.

**Comment by jeffbeckncbi** [comment]
Chris,

I'm only getting errors reported. I'll send you a test article that should give different results when run at each level. 

Jeff

**Comment by Klortho** [comment]
I _just_ changed the xslt a few minutes ago, to include info messages.  Also, make sure you use the "level" button at the top -- the default reporting level is "errors".
