### ISSUE TITLE
Logos for participating organizations

### ISSUE THREAD

**Issue by Klortho** [JATS4R/jats4r.github.io#26]
- -[x] Atypon
- -[x] British Institute of Radiology
- -[x] Cambridge University Press
- -[x] Canadian Science Publishing
- -[x] eLife
- -[x] EMBL-EBI (Europe PMC)
- -[x] F1000Research
- -[x] Frontiers
- -[x] HighWire Press
- -[ ] Nature
- -[x] NCBI
- -[x] Open Book Publishers
- -[ ] Oxford University Press
- -[x] PeerJ
- -[ ] Pensoft
- -[ ] Plazi
- -[x] PLoS
- -[x] River Valley Technologies

**Comment by seligym** [comment]
I agree, Chris.

Also, when it's time to identify our business goals, I will make the
suggestion that we consider having a JATS4R Team page, or something similar
that identifies who is behind the JATS4R work. Maybe with brief bios. This
will lend credibility to the group. I think it would also really help to
get participation, because people are more comfortable dealing with real
people, and having names and even faces behind the group will help with
that.

Mary

**Comment by Klortho** [comment]
@Melissa37 said she would get to work on this.

**Comment by Klortho** [comment]
@Melissa37 , there are a couple of logos [here](http://oaspa.org/conference/coasp-2015-preliminary-program/): PLoS and Frontiers.

**Comment by Melissa37** [comment]
Thanks Chris, so far I have logos for:
Atypon
BIR
CUP
eLife
Frontiers
Europe PMC
Where do you want me to deposit them on a GitHub repo as I get them?

Cheers
Melissa

**Comment by Klortho** [comment]
How about here, in this repo, in a subdirectory called "logos"?

**Comment by seligym** [comment]
Here is CSP's logo, attached.

Sorry for not providing sooner.

Mary

**Comment by Klortho** [comment]
Mary, I'm not sure what happens to attachments when you respond to an email from a GH issue, but I can't find it. Could you send it direct to my work email?

**Comment by Melissa37** [comment]
I have loaded all I have so far, below are the ones we still need to get (I have only requested 2 of them so far).

Chris - could you provide NCBI?

F1000Research
HighWire Press - have requested
Nature - have requested
NCBI
Open Book Publishers
Oxford University Press
Peer J
Pensoft
Plazi

**Comment by Klortho** [comment]
> Chris - could you provide NCBI?

Done.

**Comment by biancagualandi** [comment]
Hi Melissa,

Please find below OBP logo.
I'm very sorry for the delay, but I was on holiday and with limited access
to my email.

All the best,
Bianca

On Thu, September 10, 2015 9:35 am, Melissa Harrison wrote:

> Thanks Chris, so far I have logos for:
> Atypon
> BIR
> CUP
> eLife
> Frontiers
> Europe PMC
> Where do you want me to deposit them on a GitHub repo as I get them?
> 
> Cheers
> Melissa
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/JATS4R/website/issues/26#issuecomment-139168127

## 

Bianca Gualandi
Digital Product Manager
Open Book Publishers
tel: +44 1223 339929
www.openbookpublishers.com

**Comment by Melissa37** [comment]
Hi Bianca

Thanks! However, I cannot see it? Have you loaded it to: https://github.com/JATS4R/website/tree/master/logos
?

**Comment by Klortho** [comment]
@biancagualandi , attachments don't survive, when you're replying via email to a github issue. Could you email it to me directly, and I'll add it?

**Comment by Klortho** [comment]
Pursuant to Daniel's comments on the email thread, we need to figure out what to do about including these logos in the repo. Here are two solutions:
- Amend our "public domain notice" to specifically exclude the logos, and add a copyright disclaimer. I think this is easiest -- will it suffice?
- Put the logos in a separate repo, and have a copyright disclaimer there.

If nobody has an opinion, I'll implement the first one after a couple of days.

**Comment by Melissa37** [comment]
Sounds good to me!

I'll chase up the missing ones today.

M

**Comment by Klortho** [comment]
I added a checklist at the top.

**Comment by hubgit** [comment]
I've added PeerJ's logo and updated the checklist above.

**Comment by Klortho** [comment]
@Melissa37 , any luck getting Nature or Oxford University Press. I just sent a message to Terry Catapano about Plazi and Pensoft.
